steps:
 - id: create_cloud_sql_instance
   name: 'alpine'
   entrypoint: 'sh'
   args:
    - '-c'
    - |
        env | sort
        echo "**********************************************"
        echo "inside DB"
        apk add postgresql
        wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.386 -O cloud_sql_proxy
        chmod +x cloud_sql_proxy

        ./cloud_sql_proxy -instances=refined-magpie-270710:europe-west4:ci-cd-db=tcp:5432 \
                  -credential_file=proxy.json &