/*
--------------------------------------------------------------
Table Name : MIA_CW_STORE_MASTER_DATA_T
Description: Table to keep all the STORE/Department master data.
Schema     : 
Revision Hostory:
--------------------------------------------------------------
Date        |  Create By   |  CR/PR/Story   | Description
--------------------------------------------------------------
03-Jul-2020 |  SAMOH22                      | Table Created
--------------------------------------------------------------
*/

-- ##SCHEMA NAME ##--

CREATE TABLE "MIA_Schema".mia_cw_store_master_data_t(
    store_cost_center_id INTEGER default NEXTVAL('"MIA_Schema".mia_cw_store_master_data_seq'),
	country              VARCHAR(3) NOT NULL,
	unit                 VARCHAR(20) NOT NULL,
	func_department      VARCHAR(30),
	unit_location        VARCHAR(30) NOT NULL,
	delete_date          DATE,
	created_on           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	created_by           VARCHAR(10) NOT NULL DEFAULT USER,
	updated_on           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_by           VARCHAR(10) NOT NULL DEFAULT USER
);
ALTER TABLE "MIA_Schema".mia_cw_store_master_data_t ADD CONSTRAINT cw_store_master_data_pk PRIMARY KEY(store_cost_center_id);

COMMENT ON COLUMN "MIA_Schema".mia_cw_store_master_data_t.store_cost_center_id IS 'Store or cost center id which is autogenerated.';
COMMENT ON COLUMN "MIA_Schema".mia_cw_store_master_data_t.country IS 'Country name where the store belongs to.';
COMMENT ON COLUMN "MIA_Schema".mia_cw_store_master_data_t.unit IS 'Unit name of the store.';
COMMENT ON COLUMN "MIA_Schema".mia_cw_store_master_data_t.func_department IS 'Department name of the store.';
COMMENT ON COLUMN "MIA_Schema".mia_cw_store_master_data_t.unit_location IS 'City name of the store.';
COMMENT ON COLUMN "MIA_Schema".mia_cw_store_master_data_t.delete_date IS 'Delete Date, in case of the record is no more valid.';
COMMENT ON COLUMN "MIA_Schema".mia_cw_store_master_data_t.created_on IS 'When it is created.';
COMMENT ON COLUMN "MIA_Schema".mia_cw_store_master_data_t.created_by IS 'Who has created the record.';
COMMENT ON COLUMN "MIA_Schema".mia_cw_store_master_data_t.updated_on IS 'When it is updated.';
COMMENT ON COLUMN "MIA_Schema".mia_cw_store_master_data_t.updated_by IS 'Who has updated the record.';
