/*
--------------------------------------------------------------
Table Name : MIA_CW_LOCKING_DATA_T 
Description: Table to keep all the Co-Workers data related to locking functionality.
Schema     : MIA_Schema
Revision Hostory:
--------------------------------------------------------------
Date        |  Create By   |  CR/PR/Story   | Description
--------------------------------------------------------------
03-Oct-2020 |  SAMOH22                      | Table Created
--------------------------------------------------------------
*/
CREATE TABLE "MIA_Schema".mia_cw_locking_data_t(
    lockid        INTEGER default NEXTVAL('"MIA_Schema".mia_cw_locking_data_seq'),
	cw_id         VARCHAR(20) NOT NULL,
	qualification VARCHAR(30) NOT NULL,
	from_date     DATE NOT NULL,
    to_date       DATE NOT NULL,
    from_time     TIME NOT NULL,
    to_time       TIME NOT NULL,
    status        VARCHAR(10) NOT NULL,
	created_on    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	created_by    VARCHAR(10) NOT NULL DEFAULT USER,
	updated_on    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_by    VARCHAR(10) NOT NULL DEFAULT USER	
);

ALTER TABLE "MIA_Schema".mia_cw_locking_data_t ADD CONSTRAINT mia_cw_locking_data_pk PRIMARY KEY(lockid);
ALTER TABLE "MIA_Schema".mia_cw_locking_data_t ADD CONSTRAINT mia_cw_locking_qual_data_fk FOREIGN KEY(qualification) REFERENCES "MIA_Schema".mia_qualification_master_data_t (qualification);
ALTER TABLE "MIA_Schema".mia_cw_locking_data_t ADD CONSTRAINT mia_cw_locking_cwid_data_fk FOREIGN KEY(cw_id) REFERENCES "MIA_Schema".mia_cw_master_data_t (cw_id);
ALTER TABLE "MIA_Schema".mia_cw_locking_data_t ADD CONSTRAINT mia_cw_locking_data_ck CHECK (status IN ('locked', 'unlocked'));

COMMENT ON COLUMN "MIA_Schema".mia_cw_locking_data_t.lockid IS 'Unique ID whihc is autogenerated.';
COMMENT ON COLUMN "MIA_Schema".mia_cw_locking_data_t.cw_id IS 'co-worker id.';
COMMENT ON COLUMN "MIA_Schema".mia_cw_locking_data_t.qualification IS 'Qualifications.';
COMMENT ON COLUMN "MIA_Schema".mia_cw_locking_data_t.from_date IS 'From Date.';
COMMENT ON COLUMN "MIA_Schema".mia_cw_locking_data_t.to_date IS 'To Date.';
COMMENT ON COLUMN "MIA_Schema".mia_cw_locking_data_t.from_time IS 'From Time.';
COMMENT ON COLUMN "MIA_Schema".mia_cw_locking_data_t.to_time IS 'To Time.';
COMMENT ON COLUMN "MIA_Schema".mia_cw_locking_data_t.status IS 'Locking Status.';
COMMENT ON COLUMN "MIA_Schema".mia_cw_locking_data_t.created_on IS 'When it is created.';
COMMENT ON COLUMN "MIA_Schema".mia_cw_locking_data_t.created_by IS 'Who has created the record.';
COMMENT ON COLUMN "MIA_Schema".mia_cw_locking_data_t.updated_on IS 'When it is updated.';
COMMENT ON COLUMN "MIA_Schema".mia_cw_locking_data_t.updated_by IS 'Who has updated the record.';



